"""add github accounts and project repositories

Revision ID: 518662d031e3
Revises: 7fb59e922a17
Create Date: 2026-03-07 22:18:47.863128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518662d031e3'
down_revision: Union[str, Sequence[str], None] = '7fb59e922a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_github_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_repositories',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('github_account_id', sa.Uuid(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=512), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('connected_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['github_account_id'], ['user_github_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_repositories_project_id'), 'project_repositories', ['project_id'], unique=False)
    op.create_unique_constraint(None, 'project_members', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='unique')
    op.drop_index(op.f('ix_project_repositories_project_id'), table_name='project_repositories')
    op.drop_table('project_repositories')
    op.drop_table('user_github_accounts')
    # ### end Alembic commands ###
