"""add ticket system tables

Revision ID: 6dcca07134ba
Revises: 003495c5f0c7
Create Date: 2026-03-08 01:44:55.769899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcca07134ba'
down_revision: Union[str, Sequence[str], None] = '003495c5f0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('brainstorm_messages',
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='brainstormrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Enum('text', 'quiz', 'summary', 'figma_context', name='brainstormmessagetype'), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brainstorm_messages_session_id'), 'brainstorm_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_brainstorm_messages_ticket_id'), 'brainstorm_messages', ['ticket_id'], unique=False)
    op.create_table('ticket_specs',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('feature', 'design', 'plan', 'test', name='spectype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('agent_step_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_step_id'], ['workflow_steps.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_specs_ticket_id'), 'ticket_specs', ['ticket_id'], unique=False)
    op.create_table('ticket_spec_references',
    sa.Column('source_spec_id', sa.Uuid(), nullable=False),
    sa.Column('target_spec_id', sa.Uuid(), nullable=False),
    sa.Column('ref_type', sa.Enum('derives_from', 'implements', 'verifies', 'relates_to', name='specreftype'), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_spec_id'], ['ticket_specs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_spec_id'], ['ticket_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_spec_references_source_spec_id'), 'ticket_spec_references', ['source_spec_id'], unique=False)
    op.create_index(op.f('ix_ticket_spec_references_target_spec_id'), 'ticket_spec_references', ['target_spec_id'], unique=False)
    ticketsource = sa.Enum('ai_brainstorm', 'figma', 'manual', name='ticketsource', create_type=True)
    ticketsource.create(op.get_bind(), checkfirst=True)
    op.add_column('tickets', sa.Column('auto_approval', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tickets', sa.Column('source', ticketsource, server_default='manual', nullable=False))
    op.add_column('tickets', sa.Column('figma_data', sa.JSON(), nullable=True))
    op.add_column('workflow_steps', sa.Column('auto_approval', sa.Boolean(), nullable=True))
    op.add_column('workflow_steps', sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('workflow_steps', sa.Column('max_retries', sa.Integer(), server_default=sa.text('2'), nullable=False))
    op.add_column('workflow_steps', sa.Column('parent_step_id', sa.Uuid(), nullable=True))
    op.add_column('workflow_steps', sa.Column('repo_ids', sa.JSON(), nullable=True))
    op.create_foreign_key('workflow_steps_parent_step_id_fkey', 'workflow_steps', 'workflow_steps', ['parent_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflow_steps_parent_step_id_fkey', 'workflow_steps', type_='foreignkey')
    op.drop_column('workflow_steps', 'repo_ids')
    op.drop_column('workflow_steps', 'parent_step_id')
    op.drop_column('workflow_steps', 'max_retries')
    op.drop_column('workflow_steps', 'retry_count')
    op.drop_column('workflow_steps', 'auto_approval')
    op.drop_column('tickets', 'figma_data')
    op.drop_column('tickets', 'source')
    op.drop_column('tickets', 'auto_approval')
    op.drop_index(op.f('ix_ticket_spec_references_target_spec_id'), table_name='ticket_spec_references')
    op.drop_index(op.f('ix_ticket_spec_references_source_spec_id'), table_name='ticket_spec_references')
    op.drop_table('ticket_spec_references')
    op.drop_index(op.f('ix_ticket_specs_ticket_id'), table_name='ticket_specs')
    op.drop_table('ticket_specs')
    op.drop_index(op.f('ix_brainstorm_messages_ticket_id'), table_name='brainstorm_messages')
    op.drop_index(op.f('ix_brainstorm_messages_session_id'), table_name='brainstorm_messages')
    op.drop_table('brainstorm_messages')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    sa.Enum(name='ticketsource').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='specreftype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='spectype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='brainstormmessagetype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='brainstormrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
