"""add step lifecycle fields and step_reviews table

Revision ID: 7fb59e922a17
Revises: 828407979b63
Create Date: 2026-03-07 17:17:44.111165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb59e922a17'
down_revision: Union[str, Sequence[str], None] = '828407979b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_reviews',
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('diff_content', sa.Text(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'changes_requested', name='reviewstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_configs', sa.Column('default_requires_approval', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tickets', sa.Column('auto_execute', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('workflow_steps', sa.Column('requires_approval', sa.Boolean(), nullable=True))
    op.add_column('workflow_steps', sa.Column('user_prompt_override', sa.Text(), nullable=True))
    op.add_column('workflow_steps', sa.Column('brainstorm_output', sa.JSON(), nullable=True))
    op.add_column('workflow_steps', sa.Column('step_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'step_breakdown')
    op.drop_column('workflow_steps', 'brainstorm_output')
    op.drop_column('workflow_steps', 'user_prompt_override')
    op.drop_column('workflow_steps', 'requires_approval')
    op.drop_column('tickets', 'auto_execute')
    op.drop_column('agent_configs', 'default_requires_approval')
    op.drop_table('step_reviews')
    # ### end Alembic commands ###
